### ISSUE TITLE
Try out Now button present in Appearance section works differently as compared to Colors section

### ISSUE THREAD

**Issue by arsalanhub** [woozdesign/ui#259]
Steps to Reproduce:
1. Navigate to Appearance
2. Click on "Try Out Now" button. It will change complete color of application.
3. Now navigate to Colors and click on "Try Out Now" it will change only required part and color will get reset on page reload.

Excepted Behavior:
1. "Try Out Now" button on Appearance page should also change only required part .
2. Also color should get resent on page reload.

**Comment by erickim20** [comment]
Thank you. The problem has been resolved.
